Edge APIs to v1.0
microsoftgraph/microsoft-graph-devx-content pull request #337
Opened 2023-04-11 12:19 UTC by edward-day-vii

Edge APIs available in v1.0.

2023-04-17 10:19 UTC, millicentachieng requested changes

2023-04-17 10:19 UTC, millicentachieng commented on sample-queries/sample-queries.json
> +      "docLink": "https://docs.microsoft.com/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&tabs=http",
Update subdomain to `learn`.

2023-04-18 12:20 UTC, edward-day-vii commented on sample-queries/sample-queries.json
> +      "docLink": "https://docs.microsoft.com/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&tabs=http",
Updated

2023-04-19 07:40 UTC, millicentachieng approved these changes

2023-04-21 15:29 UTC, edward-day-vii commented
@millicentachieng What do I need to do to get this merged? Looks like I'm not authorized to merge here.

2023-04-24 07:58 UTC, merged